### ISSUE TITLE
VIVO-1033: Create and commit feature branch for providing JSON view of JAVA objects sent to Freemarker template for individual profile

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2717]
[Huda Khan](https://github.com/hudajkhan) (Migrated from [VIVO-1033](https://vivo-project.atlassian.net/browse/VIVO-1033)) said:

On another project, extensions to IndividualResponseBuilder were made to allow a JSON view of the JAVA objects sent to the Freemarker template.  This JSON view represents all the property information made available for an individual profile page.  This method can be integrated with the existing code within VIVO's base code.

**Comment by hudajkhan** [comment]
This approach was to enable JSON output of the data stored in a VIVO profile by converting the Freemarker JAVA objects being returned from VIVO (which included the values to be displayed for the various properties).  Since the VIVO project appears to be moving in a different direction from this approach, we can close this issue.
