### ISSUE TITLE
Links in Vitro do not work

### ISSUE THREAD

**Issue by aweissen1** [vivo-project/VIVO#3907]
Both links to VIVO and VIVO community in https://github.com/michel-heon/Vitro do not work.  

The description: "Vitro is a general-purpose web-based ontology and instance editor with customizable public browsing." is not clear to me - is Vitro a stand-alone tool to edit ontologies or does it only work in combination with VIVO? Maybe you could provide some more context on the github repo.

**Comment by chenejac** [comment]
The issue with broken links is fixed by this PR - https://github.com/vivo-project/Vitro/pull/416.

Yes, the Vitro can be use as a stand-alone tool. Vitro is a web based ontology editor which is domain agnostic, while VIVO is an application of Vitro for a specific domain (academic domain). You can find one example of application of Vitro for some other domain (culture) at https://sah.tib.eu/. If you are interested, you can self-register for Slack channels - http://bit.ly/vivo-slack and join our weekly meetings - https://wiki.lyrasis.org/display/VIVO/Development+Calls. Usually, TIB representatives participate in our calls, and they can provide you more details about https://sah.tib.eu/.
